name: Release and Build

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating releases and tags

    steps:
      # 1. Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up the Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      # 3. FIX: Use a wildcard to robustly find the go.sum for caching
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }} # Use wildcard to find go.sum
          restore-keys: |
            ${{ runner.os }}-go-

      # 4. Install Dependencies, Tidy, and Test
      - name: Install Dependencies, Tidy, and Test
        working-directory: ./test-dashboard # Run from the subdirectory
        run: |
          go mod tidy
          go test -v ./...

      # 5. Bump version and push tag
      # Note: This action may still show a deprecation warning until the author updates it.
      # This is the last remaining source of the warnings.
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      # 6. Build the application
      - name: Build Application
        working-directory: ./test-dashboard # Run from the subdirectory
        run: |
          go build -v -o ../azlo-dashboard-linux-amd64 .
          go build -v -o ../azlo-dashboard-windows-amd64.exe .
          go build -v -o ../azlo-dashboard-darwin-amd64 .

      # 7. FIX: Create Release and Upload Assets with a single, modern action
      # This replaces the old create-release and upload-release-asset steps
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          # Use the tag created in the previous step
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          # Use the changelog from the tag action for the release body
          body: ${{ steps.tag_version.outputs.changelog }}
          # Tell the action where to find the files to upload
          files: |
            ./azlo-dashboard-linux-amd64
            ./azlo-dashboard-windows-amd64.exe
            ./azlo-dashboard-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}