name: Release and Build

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      # 1. Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up the Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      # 3. Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('test-dashboard/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # 4. Install Dependencies, Tidy, and Test
      - name: Install Dependencies, Tidy, and Test
        working-directory: ./test-dashboard
        run: |
          go mod tidy
          go test -v ./...

      # 5. Bump version and push tag
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      # 6. FIX: Build the application from the correct directory
      - name: Build Application
        working-directory: ./test-dashboard # Run from the subdirectory
        run: |
          # Build the package in the current directory ('.')
          # And output the file to the parent directory ('../')
          go build -v -o ../azlo-dashboard-linux-amd64 .
          go build -v -o ../azlo-dashboard-windows-amd64.exe .
          go build -v -o ../azlo-dashboard-darwin-amd64 .

      # 7. Create a GitHub Release
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # 8. Upload Build Artifacts
      # This step expects the files in the root, which is now correct
      - name: Upload Build Artifacts
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./azlo-dashboard-*
          asset_name: azlo-dashboard-${{ runner.os }}
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}