name: Release and Build

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    # FIX 1: Grant permissions for the job to create releases and tags.
    permissions:
      contents: write

    steps:
      # 1. Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up the Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      # 3. Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          # FIX 2: Explicitly point to the go.sum in its subdirectory
          key: ${{ runner.os }}-go-${{ hashFiles('test-dashboard/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # 4. Install Dependencies and Run Tests from the root
      # No more 'working-directory'. We just tell Go where the project is.
      - name: Run Tests and Tidy Modules
        run: |
          go work init ./test-dashboard
          go work sync
          go test -v ./...
          go mod tidy

      # 5. Bump version and push tag
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      # 6. Build the application
      - name: Build Application
        run: |
          # Build from the root, telling it which package to build.
          # The output files will be created in the root.
          go build -v -o azlo-dashboard-linux-amd64 ./test-dashboard
          go build -v -o azlo-dashboard-windows-amd64.exe ./test-dashboard
          go build -v -o azlo-dashboard-darwin-amd64 ./test-dashboard

      # 7. Create a GitHub Release
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # 8. Upload Build Artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./azlo-dashboard-*
          asset_name: azlo-dashboard-${{ runner.os }}
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}