name: Release and Build

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      # 1. Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up the Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      # 3. Cache Go modules - this part was correct!
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          # This key correctly points to the go.sum in the subdirectory
          key: ${{ runner.os }}-go-${{ hashFiles('test-dashboard/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # 4. FIX: Run Go commands from the correct directory.
      # This is the main change. By setting the working-directory,
      # we ensure that 'go test' and 'go mod tidy' run where the go.mod file is.
      - name: Install Dependencies, Tidy, and Test
        working-directory: ./test-dashboard
        run: |
          go mod tidy
          go test -v ./...

      # 5. Bump version and push tag (no changes here)
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      # 6. Build the application (no changes here)
      - name: Build Application
        run: |
          go build -v -o azlo-dashboard-linux-amd64 ./test-dashboard
          go build -v -o azlo-dashboard-windows-amd64.exe ./test-dashboard
          go build -v -o azlo-dashboard-darwin-amd64 ./test-dashboard

      # 7. Create a GitHub Release (no changes here)
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # 8. Upload Build Artifacts (no changes here)
      - name: Upload Build Artifacts
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./azlo-dashboard-*
          asset_name: azlo-dashboard-${{ runner.os }}
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}