name: Release and Build

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./test-dashboard # Default for all run steps

    steps:
      # 1. Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up the Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      # 3. Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          # Correct path to the go.sum file inside the test-dashboard directory
          path: test-dashboard/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/test-dashboard/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # 4. Install Dependencies
      - name: Install Dependencies
        run: go mod tidy

      # 5. Run Go Tests
      - name: Run Go Tests
        run: go test -v ./...

      # 6. Bump version and push tag
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      # 7. Build the application
      - name: Build Application
        run: |
          go build -v -o ../azlo-dashboard-linux-amd64 .
          go build -v -o ../azlo-dashboard-windows-amd64.exe .
          go build -v -o ../azlo-dashboard-darwin-amd64 .

      # 8. Create a GitHub Release
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # 9. Upload all build artifacts to the release
      - name: Upload Build Artifacts
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }} 
          asset_path: ./azlo-dashboard-* # Artifacts are now in the root
          asset_name: azlo-dashboard-${{ runner.os }}
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}