name: Release and Build

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for creating releases and tags

    steps:
      # 1. Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up the Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      # 3. Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # 4. Install Dependencies, Tidy, and Test
      - name: Install Dependencies, Tidy, and Test
        working-directory: ./test-dashboard
        run: |
          go mod tidy
          go test -v ./...

      # 5. Bump version and push tag
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      # 6. Build the application
      - name: Build Application
        working-directory: ./test-dashboard
        run: |
          # Build for Linux (amd64)
          GOOS=linux GOARCH=amd64 go build -v -o ../azlo-dashboard-linux-amd64 .
          
          # Build for Windows (amd64)
          GOOS=windows GOARCH=amd64 go build -v -o ../azlo-dashboard-windows-amd64.exe .
          
          # Build for macOS (amd64)
          GOOS=darwin GOARCH=amd64 go build -v -o ../azlo-dashboard-darwin-amd64 .

      # 7. Create Release and Upload Assets
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          # The list of files to upload reflects the standard build output
          files: |
            ./azlo-dashboard-linux-amd64
            ./azlo-dashboard-windows-amd64.exe 
            ./azlo-dashboard-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}